# Generated by Django 4.1.2 on 2023-01-09 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_orderitem_date_added_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='date_ordered',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='date_ordered',
            new_name='date_added',
        ),
    ]
