# Generated by Django 4.1.2 on 2023-01-09 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_rename_color_product_producttitle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ProductTitle',
            new_name='name',
        ),
    ]
